### ISSUE TITLE
ntEdit on SNPs

### ISSUE THREAD

**Issue by dcopetti** [bcgsc/ntEdit#12]
Hi Rene,
After reading the paper I wonder how ntEdit will behave when finding in the assembly a position that in the reads is heterozygous (e.g. a SNP).
I don't see the case being discussed, so I wonder what will happen with a haploid reference and reads from a diploid (with any degree of heterozygosity) organism.
Thanks,
Dario

**Comment by warrenlr** [comment]
Hi Dario,

With either a haploid or pseudo-haploid assembly, heterozygous positions WILL NOT BE FLAGGED by ntEdit when using a MATCHING, diploid read set, as long as a sufficient subset of k kmers is found missing at that position, together with a sufficient subset of k kmers available to change. 

If you are using an UNMATCHED pseudo-haploid assembly and read data, heterozygous positions MAY OR MAY NOT BE FLAGGED by ntEdit. That's because it depends whether the allelic base chosen in the pseudo hap assembly has a match in the diploid read set from a different individual or species. 

This is why we describe the main application in the manuscript as identifying/correcting homozygous base errors with matching data. We also showcase an application whereby we turn a pseudo-haploid spruce assembly into its haploid equivalent using a purely haploid read source where allelic differences are not in the haploid read set.

To achieve what you suggest with ntEdit is tricky and not possible without checking for alternate kmer subsets at EVERY single position (regardless of whether they are missing in the diploid read set), which can be costly on large genomes. We explored this in a prototype but decided to focus on error-correction as the main application.   

An easier problem is to profile shared variants between species (or individuals), by using a modified (unpublished) version with two Bloom filters, with the first consisting of a diploid read set from a different species (individual) and the second one consisting of the diploid read set corresponding to the pseudo-hap assembly. We have a working prototype of this, which is fairly fast. This is a good way to identify homozygous SNP/SNV with ntEdit but it won't give you whether shared bases are homozygous or heterozygous at those positions.

Hope this helps
Rene

**Comment by dcopetti** [comment]
yes, thank you for the details!

Dario
