### ISSUE TITLE
How much does a short read assembly benefit from ntEdit

### ISSUE THREAD

**Issue by ms-gx** [bcgsc/ntEdit#19]
In your experience, if I have a short-read assembly (Illumina PE150bp) assembled with ABySS: How much does the assembly in general profit from polishing with ntEdit? Would you recommend it? Why/Why not?

I will try on my assemblies anyway, but would like to hear your experience.

**Comment by warrenlr** [comment]
Thank you for your message and interest in ntedit.

Marginal benefit, if any*.  If you do, I would recommend running with two Bloom filters, the second one comprising repeat kmers (please consult guidelines on how to select proper k with specific jump j values).  That's because ntEdit operates with less context than alignment-based polishers like Pilon or Racon and some underrepresented kmers may be incorrectly changed for abundant (repeated) ones.  I would also advise you to monitor the changes closely, say with BUSCO or another means to evaluate the resulting assemblies.

* It depends on a lot of factors and in some cases, even though not substantial, short read assembly polishing with ntedit is beneficial (see the example of a [beluga supernova 10xG linked read assembly](https://warrenlr.github.io/papers/ntedit_ismb2019.pdf) )

**Comment by ms-gx** [comment]
Thanks for your comment, this is really helpful!

Yes, we are always using BUSCO, N50, mapping rate or raw data and whatever we can use to asses the quality of the assembly :)
