### ISSUE TITLE
ntEdit for assemblies with really high error rates

### ISSUE THREAD

**Issue by shelkmike** [bcgsc/ntEdit#20]
The assembler Miniasm produces assemblies with the same error rate as in long reads. Can ntEdit be used to polish assemblies with error rate, like, 10%? How to optimise ntEdit parameters to do this? Maybe a user should reduce the k-mer size?

**Comment by warrenlr** [comment]
this isn't ideal.  
Success would depend on many factors, including:
1. how are errors distributed along your WGA
2. source of kmers for ntedit (do you have access to matching short reads to build Bloom filters from?)
3. kmer length

Fixing a SMS assembly with long read kmers is not a typical ntedit use case. Ideally, you would want an SMS assembly built with a tool like shasta (preferably) or redbean and a source of kmers from a matching short read dataset. 

Now we have done some tests at k25 on a redbean and shasta NA12878 human assembly, using only nanopore reads as source of kmers (nthits -c1 and -c2 gave best results).  Although our tests worked (we ran BUSCO as a proxy for assembly quality, recovering 15-20% complete BUSCO genes), the accuracy of the resulting assembly was much lower than when using short reads.  

If you wish to try running ntedit on longreads as kmer source I recommend, as a first trial, to run ntedit iteratively, at least 3 different kmer sizes, eg. k25, k22, k19 where the output of the largerk assembly be the input to the next. If at all possible, regenerate your base long read assembly with shasta.

good luck!

**Comment by shelkmike** [comment]
@warrenlr 
Thank you. I mean polishing of a long read assembly using k-mers from short reads. 
Also, I wonder, why do you recommend to use longer k-mers for the first iteration? If there is a region like this
`[error 1][18 bp without errors][error 2][10 bp without errors][error 3][10 bp without errors][error 4]`
then error 3 will be successfully polished if the iterations go in the order 19, 22, 25, but not if they go in the order 25, 22, 19 (if I understand the algorithm of ntEdit correctly).

**Comment by warrenlr** [comment]
the reason for the long to short k recommendation is to mitigate errors.  longer kmers will have more specificity. 
Going low to long risks introducing errors (eg. from repeat kmers)

That said, I have never fully tested this theory. I invite you to perform your own tests, you might prove me wrong on your dataset.

Since your kmer source is from short reads, you may increase the k values I indicated. I only presented them as a guide, without knowledge of your data or your experimental design. Again, I invite you to test a range of kmers that may be better suited with your particular data.

**Comment by shelkmike** [comment]
@warrenlr 
Thank you
