### ISSUE TITLE
Indeterministic behavior of ntEdit

### ISSUE THREAD

**Issue by shelkmike** [bcgsc/ntEdit#23]
If I run ntEdit 1.3.5 two times with the same parameters on the same set of contigs, the results will be different. Is there a way to make ntEdit deterministic?

**Comment by warrenlr** [comment]
I just performed tests to verify your claim using _C. elegans_ controlled data 

1) I ran ntedit in triplicates using the same Bloom filter, and get the same (deterministic) results.

2) I also ran the whole pipeline again, generating another Bloom filter with nthits and running ntedit in triplicate. I compared the output within the replicates and to the run done in (1), and I confirm the same (deterministic) behavior.

3) I re-ran (2) using 12 threads. The output in the "changes.tsv" is inconsistent with that of the other runs, as expected since threads are assigned different contigs to polish and do not finish in the same order.  After sorting the output, I compared the .tsv file and the output is again identical, confirming the deterministic behaviour.

When you did your test, did you re-use the Bloom filter or ran the whole pipeline (with nthits) anew?  Although my tests didn't show disagreement, I suspect that a disagreement in output between identical parameter runs would likely stem from the Bloom filter, as hash collisions could arise in subsequent nthits runs. A way to minimize is to make sure your Bloom filters are no where near saturation (i.e. use nthits -b 36 to ensure a low FPR). If you re-use the Bloom filter between different, same-parameter, ntedit runs you should not observe any change in output.

Thank you for your message and interest in ntEdit.
Rene

**Comment by shelkmike** [comment]
Thank you for the answer. Now I realized that ntEdit shuffles contigs and their order is different in different runs. So, to make the output of ntEdit deterministic I will sort the polished contigs by their titles.
