### ISSUE TITLE
Specify read files not on CWD

### ISSUE THREAD

**Issue by fgvieira** [bcgsc/ntEdit#72]
Is it possible to specify reads files that are not in the current working directory?

**Comment by lcoombe** [comment]
Hi @fgvieira,

Currently, the reads files need to be in the current working directory, as the driver script will search this directory for input reads files with the supplied prefix. You can always make soft-links to the reads if they are located elsewhere.

Hope that helps - thank you for your interest in ntEdit!
Lauren

**Comment by fgvieira** [comment]
I want to run ntEdit as part as a bigger workflow, and it would be nice to be able to directly refer to the reads files, just like with the drafts file.
Would it be possible to either:
- specify the reads files directly (e.g. `--reads /path/to/file_R1.fq.gz /path/to/file_R2.fq.gz /path/to/file_other.fq.gz`)
- allow the prefix to include a path (e.g. `--reads /path/to/file`)

**Comment by lcoombe** [comment]
Hi @fgvieira,

I had some time, so I made some tweaks so that you can provide a relative or absolute path with the reads prefix when supplying `--reads` - this would have the behaviour of your second suggestion. Note that all output files will still be output in the current working directory.
This change is in release v2.1.1.
